/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.salesmate.component;

import com.salesmate.controller.ProductController;
import com.salesmate.model.Product;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author meiln
 */
public class AdDashboard extends javax.swing.JPanel {

    private ProductController productController;

    /**
     * Creates new form DashboardPanel
     */
    public AdDashboard() {
        initComponents();
        productController = new ProductController();
        loadLowStockProducts();
        loadInventoryManagement(); // Gọi phương thức để tải dữ liệu quản lý tồn kho
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("Hiển thị user, product, invoice + sp bán chạy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel3)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tổng quan bán hàng", jPanel1);

        jLabel2.setText("Tổng doanh thu theo thời gian + biểu đồ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(249, 249, 249))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê doanh thu", jPanel2);

        // Thêm LowStockPanel vào tab "Cảnh báo hết hàng"
        jTabbedPane1.addTab("Cảnh báo hết hàng", new LowStockPanel());

        // Thêm InventoryManagementPanel vào tab "Quản lý tồn kho"
        jTabbedPane1.addTab("Quản lý tồn kho", new InventoryManagementPanel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadLowStockProducts() {
        List<Product> lowStockProducts = productController.getLowStockProducts();
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Tên sản phẩm", "Số lượng", "Giá"}, 0);

        if (lowStockProducts.isEmpty()) {
            model.addRow(new Object[]{"Không có sản phẩm", "", "", ""});
        } else {
            for (Product product : lowStockProducts) {
                model.addRow(new Object[]{
                        product.getProductId(),
                        product.getProductName(),
                        product.getQuantity(),
                        product.getPrice()
                });
            }
        }

        JTable table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(scrollPane, java.awt.BorderLayout.CENTER);
    }

    private void loadInventoryManagement() {
        List<Product> inventoryProducts = productController.getInventoryForecast();
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Tên sản phẩm", "Số lượng", "Giá"}, 0);

        for (Product product : inventoryProducts) {
            model.addRow(new Object[]{
                    product.getProductId(),
                    product.getProductName(),
                    product.getQuantity(),
                    product.getPrice()
            });
        }

        JTable table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(scrollPane, java.awt.BorderLayout.CENTER);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
