/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.salesmate.component;

/**
 *
 * @author meiln
 */
public class AdDashBoard extends javax.swing.JPanel {

    /**
     * Creates new form AdDashBoard
     */
    public AdDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spAdmin = new javax.swing.JScrollPane();
        panelAdmin = new javax.swing.JPanel();
        panelStatistic = new javax.swing.JPanel();
        panelUserCount = new javax.swing.JPanel();
        panelProductCount = new javax.swing.JPanel();
        panelInvoiceCount = new javax.swing.JPanel();
        spBestSellingTable = new javax.swing.JScrollPane();
        tbBestSelling = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        spAdmin.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        spAdmin.setToolTipText("");
        spAdmin.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        spAdmin.setViewportView(panelAdmin);

        panelStatistic.setLayout(new javax.swing.BoxLayout(panelStatistic, javax.swing.BoxLayout.X_AXIS));

        panelUserCount.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout panelUserCountLayout = new javax.swing.GroupLayout(panelUserCount);
        panelUserCount.setLayout(panelUserCountLayout);
        panelUserCountLayout.setHorizontalGroup(
            panelUserCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        panelUserCountLayout.setVerticalGroup(
            panelUserCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        panelStatistic.add(panelUserCount);

        panelProductCount.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panelProductCountLayout = new javax.swing.GroupLayout(panelProductCount);
        panelProductCount.setLayout(panelProductCountLayout);
        panelProductCountLayout.setHorizontalGroup(
            panelProductCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        panelProductCountLayout.setVerticalGroup(
            panelProductCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        panelStatistic.add(panelProductCount);

        panelInvoiceCount.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelInvoiceCountLayout = new javax.swing.GroupLayout(panelInvoiceCount);
        panelInvoiceCount.setLayout(panelInvoiceCountLayout);
        panelInvoiceCountLayout.setHorizontalGroup(
            panelInvoiceCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        panelInvoiceCountLayout.setVerticalGroup(
            panelInvoiceCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        panelStatistic.add(panelInvoiceCount);

        tbBestSelling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spBestSellingTable.setViewportView(tbBestSelling);

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spBestSellingTable, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
            .addComponent(panelStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addComponent(panelStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spBestSellingTable, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        spAdmin.setViewportView(panelAdmin);

        add(spAdmin);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelInvoiceCount;
    private javax.swing.JPanel panelProductCount;
    private javax.swing.JPanel panelStatistic;
    private javax.swing.JPanel panelUserCount;
    private javax.swing.JScrollPane spAdmin;
    private javax.swing.JScrollPane spBestSellingTable;
    private javax.swing.JTable tbBestSelling;
    // End of variables declaration//GEN-END:variables
}
