package com.salesmate.component;
import com.salesmate.view.AdminView;

import org.apache.batik.swing.JSVGCanvas;
import java.awt.*;

import com.salesmate.utils.ColorPalette;
import com.salesmate.utils.SessionManager;
import com.salesmate.view.LoginForm;
import java.awt.Image;
import java.awt.geom.Ellipse2D;
import javax.swing.ImageIcon;
import java.beans.Beans;

public class AdminSidebar extends javax.swing.JPanel {

      private AdminView parentView;

    public AdminSidebar() {
        initComponents();
    }
  public void setParentView(AdminView parentView) {
        this.parentView = parentView;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tbtnDashBoard = new javax.swing.JToggleButton();
        tbtnUser = new javax.swing.JToggleButton();
        tbtnProduct = new javax.swing.JToggleButton();
        tbtnInvoice = new javax.swing.JToggleButton();
        tbtnRevenue = new javax.swing.JToggleButton();

        buttonGroup1.add(tbtnDashBoard);
        tbtnDashBoard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/ic_dashboard.png"))); // NOI18N
        tbtnDashBoard.setText("DASHBOARD");
        tbtnDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnDashBoardActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtnUser);
        tbtnUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/ic_user.png"))); // NOI18N
        tbtnUser.setText("NHÂN VIÊN");
        tbtnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnUserActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtnProduct);
        tbtnProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/ic_product.png"))); // NOI18N
        tbtnProduct.setText("SẢN PHẨM");
        tbtnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnProductActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtnInvoice);
        tbtnInvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/ic_invoice.png"))); // NOI18N
        tbtnInvoice.setText("HÓA ĐƠN");
        tbtnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnInvoiceActionPerformed(evt);
            }
        });

        buttonGroup1.add(tbtnRevenue);
        tbtnRevenue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
      tbtnRevenue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/ic_qlyuser.png")));
tbtnRevenue.setText("NGƯỜI DÙNG");

        tbtnRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnRevenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbtnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtnInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbtnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tbtnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tbtnUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tbtnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tbtnInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tbtnRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents
@Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    // Vẽ gradient background cho sidebar
    Graphics2D g2d = (Graphics2D) g;
    GradientPaint gradient = new GradientPaint(
            0, 0, ColorPalette.WARNING, // Màu vàng nhạt từ ColorPalette
            0, getHeight(), new Color(255, 204, 0) // Màu vàng đậm (có thể điều chỉnh theo yêu cầu)
    );
    g2d.setPaint(gradient);
    g2d.fillRect(0, 0, getWidth(), getHeight()); // Vẽ gradient nền
}



    private void tbtnDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnDashBoardActionPerformed
      parentView.switchCard("cardDashBoard"); // AdDashboard

    }//GEN-LAST:event_tbtnDashBoardActionPerformed

    private void tbtnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnUserActionPerformed
         parentView.switchCard("cardUserPanel"); // AdUserPanel
    }//GEN-LAST:event_tbtnUserActionPerformed

    private void tbtnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnProductActionPerformed
       parentView.switchCard("cardProductPanel"); // AdProductPanel
    }//GEN-LAST:event_tbtnProductActionPerformed

    private void tbtnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnInvoiceActionPerformed
       parentView.switchCard("cardInvoicePanel"); // AdInvoicePanel
    }//GEN-LAST:event_tbtnInvoiceActionPerformed

    private void tbtnRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnRevenueActionPerformed
         parentView.switchCard("cardRevenuePanel"); // AdDoanhthuPanel
    }//GEN-LAST:event_tbtnRevenueActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton tbtnDashBoard;
    private javax.swing.JToggleButton tbtnInvoice;
    private javax.swing.JToggleButton tbtnProduct;
    private javax.swing.JToggleButton tbtnRevenue;
    private javax.swing.JToggleButton tbtnUser;
    // End of variables declaration//GEN-END:variables
}
