/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.salesmate.component;

/**
 *
 * @author meiln
 */
public class AdRevenuePanel extends javax.swing.JPanel {

    /**
     * Creates new form AdReportPanel
     */
    public AdRevenuePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpRevenue = new javax.swing.JTabbedPane();
        panelRevenueCal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRevenueReport = new javax.swing.JPanel();

        jLabel1.setText("Tiính doanh thu");

        javax.swing.GroupLayout panelRevenueCalLayout = new javax.swing.GroupLayout(panelRevenueCal);
        panelRevenueCal.setLayout(panelRevenueCalLayout);
        panelRevenueCalLayout.setHorizontalGroup(
            panelRevenueCalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRevenueCalLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        panelRevenueCalLayout.setVerticalGroup(
            panelRevenueCalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRevenueCalLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        tpRevenue.addTab("Table", panelRevenueCal);

        javax.swing.GroupLayout panelRevenueReportLayout = new javax.swing.GroupLayout(panelRevenueReport);
        panelRevenueReport.setLayout(panelRevenueReportLayout);
        panelRevenueReportLayout.setHorizontalGroup(
            panelRevenueReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelRevenueReportLayout.setVerticalGroup(
            panelRevenueReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        tpRevenue.addTab("Report", panelRevenueReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpRevenue)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpRevenue)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelRevenueCal;
    private javax.swing.JPanel panelRevenueReport;
    private javax.swing.JTabbedPane tpRevenue;
    // End of variables declaration//GEN-END:variables
}
