/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.salesmate.component;

import com.salesmate.controller.UserController;
import com.salesmate.model.User;
import com.salesmate.utils.SessionManager;

import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;

/**
 *
 * @author Nhan
 */
public class CashierAccount extends javax.swing.JPanel {

    private final UserController userController;
    private final SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    private String selectedAvatarPath = null;
    private int avatarSize = 250; // Default avatar size updated to 250x250

    /**
     * Creates new form CashierAccount
     */
    public CashierAccount() {
        initComponents();
        userController = new UserController();

        // Add a ComponentListener to ensure the avatar is resized after rendering
        lblAvatar.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                resizeAvatar();
            }
        });

        // Add a MouseWheelListener to handle zoom functionality
        lblAvatar.addMouseWheelListener(new MouseWheelListener() {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                int notches = e.getWheelRotation();
                if (notches < 0) {
                    avatarSize += 10; // Zoom in
                } else if (notches > 0 && avatarSize > 50) {
                    avatarSize -= 10; // Zoom out (minimum size 50x50)
                }
                resizeAvatar(); // Ensure the avatar is resized dynamically
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmUpdateDialog = new javax.swing.JDialog();
        AccountPanel = new javax.swing.JPanel();
        UserInfoPanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblPW = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        HeaderSPR = new javax.swing.JSeparator();
        lblUserHeader = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblCCCD = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        txtPW = new javax.swing.JPasswordField();
        InfoSPR = new javax.swing.JSeparator();
        btnResetPW = new javax.swing.JButton();
        UserAvatarPanel = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        lblCreateAt = new javax.swing.JLabel();
        AvatarSpt = new javax.swing.JSeparator();
        lblCreateAtValue = new javax.swing.JLabel();
        lblStatusValue = new javax.swing.JLabel();
        btnUpdateAvatar = new javax.swing.JButton();
        lblAvatar = new javax.swing.JLabel();

        javax.swing.GroupLayout ConfirmUpdateDialogLayout = new javax.swing.GroupLayout(ConfirmUpdateDialog.getContentPane());
        ConfirmUpdateDialog.getContentPane().setLayout(ConfirmUpdateDialogLayout);
        ConfirmUpdateDialogLayout.setHorizontalGroup(
            ConfirmUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        ConfirmUpdateDialogLayout.setVerticalGroup(
            ConfirmUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        AccountPanel.setBackground(new java.awt.Color(220, 240, 242));

        UserInfoPanel.setBackground(new java.awt.Color(23, 162, 184));
        UserInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsername.setBackground(new java.awt.Color(241, 241, 241));
        lblUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Tên người dùng");

        txtCCCD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCCCD.setText("0123456789");
        txtCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCCDActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblEmail.setText("Email");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setText("Unknown");
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtEmail.setText("Forexample@gmail.com");

        lblPW.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPW.setText("Mật khẩu");

        btnUpdate.setBackground(new java.awt.Color(255, 193, 7));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Cập nhật");

        btnSave.setBackground(new java.awt.Color(40, 167, 69));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblUserHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUserHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblUserHeader.setText("THÔNG TIN TÀI KHOẢN");

        lblDOB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblDOB.setText("Ngày sinh");

        lblCCCD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCCCD.setText("CCCD");

        txtDOB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDOB.setText("01/01/2003");
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        txtPW.setText("jPasswordField1");

        btnResetPW.setBackground(new java.awt.Color(102, 0, 51));
        btnResetPW.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetPW.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPW.setText("Đổi mật khẩu");
        btnResetPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserInfoPanelLayout = new javax.swing.GroupLayout(UserInfoPanel);
        UserInfoPanel.setLayout(UserInfoPanelLayout);
        UserInfoPanelLayout.setHorizontalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInfoPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HeaderSPR)
                    .addComponent(InfoSPR, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCCCD)
                            .addComponent(txtEmail)
                            .addComponent(txtPW)
                            .addComponent(txtDOB)
                            .addComponent(txtUsername)))
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                                .addComponent(lblUserHeader)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInfoPanelLayout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(btnResetPW, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        UserInfoPanelLayout.setVerticalGroup(
            UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblUserHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HeaderSPR)
                .addGap(3, 3, 3)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserInfoPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(InfoSPR, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnResetPW, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        UserAvatarPanel.setBackground(new java.awt.Color(255, 255, 255));
        UserAvatarPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblStatus.setText("Trạng thái");

        lblCreateAt.setText("Ngày tạo");

        lblCreateAtValue.setText("01/01/2003");

        lblStatusValue.setText("Hoạt động");

        btnUpdateAvatar.setBackground(java.awt.SystemColor.textHighlight);
        btnUpdateAvatar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateAvatar.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateAvatar.setText("Đổi ảnh đại diện");
        btnUpdateAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAvatarActionPerformed(evt);
            }
        });

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avt/N (2).jpg"))); // NOI18N

        javax.swing.GroupLayout UserAvatarPanelLayout = new javax.swing.GroupLayout(UserAvatarPanel);
        UserAvatarPanel.setLayout(UserAvatarPanelLayout);
        UserAvatarPanelLayout.setHorizontalGroup(
            UserAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserAvatarPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(UserAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(AvatarSpt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdateAvatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(UserAvatarPanelLayout.createSequentialGroup()
                        .addGroup(UserAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserAvatarPanelLayout.createSequentialGroup()
                                .addComponent(lblCreateAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9))
                            .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UserAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreateAtValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        UserAvatarPanelLayout.setVerticalGroup(
            UserAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserAvatarPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(btnUpdateAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(AvatarSpt, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(UserAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateAtValue)
                    .addComponent(lblCreateAt))
                .addGap(6, 6, 6)
                .addGroup(UserAvatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lblStatusValue))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(UserAvatarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(UserInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserAvatarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        add(AccountPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        updateUserData(); // Save updated user data when the Save button is clicked
    }

    private void btnResetPWActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JDialog changePasswordDialog = new javax.swing.JDialog();
        changePasswordDialog.setTitle("Change Password");
        changePasswordDialog.setModal(true);
        changePasswordDialog.setSize(500, 350); // Increased size for better spacing
        changePasswordDialog.setLocationRelativeTo(this);

        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.GridBagLayout());
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)); // Add padding

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(10, 10, 10, 10); // Add spacing between components
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;

        javax.swing.JLabel lblOldPassword = new javax.swing.JLabel("Mật khẩu cũ:");
        lblOldPassword.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16)); // Larger font
        javax.swing.JPasswordField txtOldPassword = new javax.swing.JPasswordField(40); // Longer input field
        txtOldPassword.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16)); // Larger font

        javax.swing.JLabel lblNewPassword = new javax.swing.JLabel("Mật khẩu mới:");
        lblNewPassword.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16)); // Larger font
        javax.swing.JPasswordField txtNewPassword = new javax.swing.JPasswordField(40); // Longer input field
        txtNewPassword.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16)); // Larger font

        javax.swing.JLabel lblConfirmPassword = new javax.swing.JLabel("Xác nhận mật khẩu:");
        lblConfirmPassword.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16)); // Larger font
        javax.swing.JPasswordField txtConfirmPassword = new javax.swing.JPasswordField(40); // Longer input field
        txtConfirmPassword.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16)); // Larger font

        javax.swing.JButton btnSubmit = new javax.swing.JButton("Đổi mật khẩu");
        btnSubmit.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16)); // Larger font
        btnSubmit.setBackground(new java.awt.Color(40, 167, 69)); // Green color
        btnSubmit.setForeground(java.awt.Color.WHITE);

        javax.swing.JButton btnCancel = new javax.swing.JButton("Huỷ");
        btnCancel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16)); // Larger font
        btnCancel.setBackground(new java.awt.Color(220, 53, 69)); // Red color
        btnCancel.setForeground(java.awt.Color.WHITE);

        // Add components to the panel
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel.add(lblOldPassword, gbc);

        gbc.gridx = 1;
        panel.add(txtOldPassword, gbc);

        gbc.gridx = 0;
        gbc.gridy = 1;
        panel.add(lblNewPassword, gbc);

        gbc.gridx = 1;
        panel.add(txtNewPassword, gbc);

        gbc.gridx = 0;
        gbc.gridy = 2;
        panel.add(lblConfirmPassword, gbc);

        gbc.gridx = 1;
        panel.add(txtConfirmPassword, gbc);

        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 0)); // Increased spacing between buttons
        buttonPanel.add(btnSubmit);
        buttonPanel.add(btnCancel);

        panel.add(buttonPanel, gbc);

        changePasswordDialog.add(panel);

        // Add action listeners
        btnSubmit.addActionListener(e -> {
            String oldPassword = new String(txtOldPassword.getPassword());
            String newPassword = new String(txtNewPassword.getPassword());
            String confirmPassword = new String(txtConfirmPassword.getPassword());

            User loggedInUser = SessionManager.getInstance().getLoggedInUser();
            if (loggedInUser == null) {
                JOptionPane.showMessageDialog(this, "No user is logged in.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String currentPassword = loggedInUser.getPassword();
            if (currentPassword == null || !currentPassword.equals(oldPassword)) {
                JOptionPane.showMessageDialog(this, "Old password is incorrect.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!newPassword.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(this, "New password and confirmation do not match.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            loggedInUser.setPassword(newPassword);
            boolean isUpdated = userController.updateUser(loggedInUser);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Password updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                changePasswordDialog.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update password.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        btnCancel.addActionListener(e -> changePasswordDialog.dispose());

        changePasswordDialog.setVisible(true);
    }

    private void resizeAvatar() {
        if (lblAvatar.getWidth() > 0 && lblAvatar.getHeight() > 0) {
            ImageIcon originalIcon = null;

            // Check if a new avatar is selected
            if (selectedAvatarPath != null) {
                originalIcon = new ImageIcon(selectedAvatarPath);
            } else {
                User loggedInUser = SessionManager.getInstance().getLoggedInUser();
                if (loggedInUser != null && loggedInUser.getAvatar() != null) {
                    originalIcon = new ImageIcon(getClass().getResource("/img/avt/" + loggedInUser.getAvatar()));
                }
            }

            if (originalIcon != null) {
                // Resize the avatar to the current avatarSize
                Image resizedImage = originalIcon.getImage().getScaledInstance(avatarSize, avatarSize, Image.SCALE_SMOOTH);
                lblAvatar.setIcon(new ImageIcon(resizedImage));
            }
        }
    }

    private void loadUserData() {
        User loggedInUser = SessionManager.getInstance().getLoggedInUser();
        if (loggedInUser != null) {
            txtUsername.setText(loggedInUser.getUsername());
            txtEmail.setText(loggedInUser.getEmail());
            txtDOB.setText(loggedInUser.getCreatedAt() != null ? dateFormat.format(loggedInUser.getCreatedAt()) : "");
            txtCCCD.setText(loggedInUser.getStatus());
            lblStatusValue.setText(loggedInUser.getStatus());
            lblCreateAtValue.setText(loggedInUser.getCreatedAt() != null ? dateFormat.format(loggedInUser.getCreatedAt()) : "");
            resizeAvatar(); // Ensure the avatar is resized when loading user data
        } else {
            JOptionPane.showMessageDialog(this, "No user is logged in.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnUpdateAvatarActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            selectedAvatarPath = selectedFile.getAbsolutePath();
            resizeAvatar(); // Resize the avatar after selecting a new image
        }
    }

    private void updateUserData() {
        User loggedInUser = SessionManager.getInstance().getLoggedInUser();
        if (loggedInUser != null) {
            loggedInUser.setUsername(txtUsername.getText());
            loggedInUser.setEmail(txtEmail.getText());
            loggedInUser.setStatus(txtCCCD.getText());

            if (selectedAvatarPath != null) {
                try {
                    String avatarFileName = new File(selectedAvatarPath).getName();
                    File destination = new File(getClass().getResource("/img/avt/").getPath() + avatarFileName);
                    Files.copy(new File(selectedAvatarPath).toPath(), destination.toPath(), StandardCopyOption.REPLACE_EXISTING);
                    loggedInUser.setAvatar(avatarFileName);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Failed to update avatar.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            boolean isUpdated = userController.updateUser(loggedInUser);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "User information updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update user information.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No user is logged in.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JSeparator AvatarSpt;
    private javax.swing.JDialog ConfirmUpdateDialog;
    private javax.swing.JSeparator HeaderSPR;
    private javax.swing.JSeparator InfoSPR;
    private javax.swing.JPanel UserAvatarPanel;
    private javax.swing.JPanel UserInfoPanel;
    private javax.swing.JButton btnResetPW;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateAvatar;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblCreateAt;
    private javax.swing.JLabel lblCreateAtValue;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusValue;
    private javax.swing.JLabel lblUserHeader;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPW;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
